# Generated by Django 6.1 on 2026-08-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leave_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='WORKPULSE', max_length=150)),
                ('annual_leave_limit', models.PositiveIntegerField(default=15, help_text='Maximum paid leave allowed per employee per year.')),
                ('deduction_enabled', models.BooleanField(default=True)),
                ('working_days_per_month', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Policy',
                'verbose_name_plural': 'Company Policy',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
