# Generated by Django 6.1 on 2026-08-24 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companypolicy_employee_monthly_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypolicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use the first day of the payroll month.')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('working_days', models.PositiveIntegerField(default=30)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.employee')),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'month'), name='unique_employee_payroll_per_month')],
            },
        ),
    ]
