# Generated by Django 6.1 on 2026-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_companypolicy_options_alter_leave_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypolicy',
            options={'verbose_name': 'Company Policy', 'verbose_name_plural': 'Company Policies'},
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
