# Generated by Django 6.1 on 2026-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_companypolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='present_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
